name: DeepAPP
description: Deep API Calls using Flutter!.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  image_picker_modern: ^0.4.12+2
  http: ^0.12.1
  logger: ^0.9.1
  path_provider: ^1.6.11
  wc_flutter_share: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true
